baseURL: "https://time-friend.com/"
defaultContentLanguage: "en"
defaultContentLanguageInSubdir: true
theme: "hugo-brewm"
enableGitInfo: true
enableRobotsTXT: true

module:
  mounts:
    - source: content/en
      target: content
      lang: en
    - source: content
      target: content
      lang: zh
      excludeFiles: 'en/**'

languages:
  en:
    weight: 1
    languageCode: en-GB
    languageName: English
    title: Be Your Time Friend
    params:
      description: "Keep learning, keep blogging."
    pagination:
      pagerSize: 8
      path: page
    menu:
      main:
        - identifier: home
          name: Home
          url: /en/
          weight: 1
        - identifier: archive
          name: Archive
          url: /en/archive/
          weight: 2
        - identifier: tags
          name: Tags
          url: /en/tags/
          weight: 3
        - identifier: about
          name: About
          url: /en/about/
          weight: 4
        - identifier: github
          name: GitHub
          url: https://github.com/0x1428571429
          weight: 5
  zh:
    weight: 2
    languageCode: zh-CN
    languageName: 中文
    title: Be Your Time Friend
    params:
      description: "Keep learning, keep blogging."
    pagination:
      pagerSize: 8
      path: page
    menu:
      main:
        - identifier: home
          name: 首页
          url: /zh/
          weight: 1
        - identifier: archive
          name: 归档
          url: /zh/archive/
          weight: 2
        - identifier: tags
          name: 标签
          url: /zh/tags/
          weight: 3
        - identifier: about
          name: 关于
          url: /zh/about/
          weight: 4
        - identifier: github
          name: GitHub
          url: https://github.com/0x1428571429
          weight: 5

params:
  title: Be Your Time Friend
  description: "Keep learning, keep blogging."
  copyright: "Copyright 2024 © 0x1428571429"
  HideHugoCredit: true
  extMeta: true

  author:
    name: 0x1428571429
    email: incomparable9527@foxmail.com

  feed:
    flowlines: false

  posts:
    colophon: true

  logo:
    logoType: true

  search:
    enable: false
    pagefind: false

permalinks:
  archive: archive/:slug/

markup:
  goldmark:
    renderer:
      unsafe: true
  defaultMarkdownHandler: goldmark

taxonomies:
  tag: "tags"
  category: "categories"

outputs:
  home: ["HTML", "RSS", "JSON"]
